### ISSUE TITLE
PCB and SMD soldering

### ISSUE THREAD

**Issue by amchagas** [pyPhotometry/hardware#1]
Hi Thomas,

We are going to implement one unit of PyPhotometry here at Sussex, and after taking a look at the hardware documentation, I was wondering how you soldered the boards? 
Did you use a stencil for placing the SMD components or did you solder them by hand? If you used a stencil, are the files to generate one available with the gerber zip file?

Thanks!

**Comment by ThomasAkam** [comment]
Hi Andre,

I hand soldered the prototype boards so did not make a stencil, but I think the file needed to generate a stencil is file  _pyPhotometry_1.0.2.gtp_ file in the gerber zip.

**Comment by amchagas** [comment]
Thanks!
